# Generated by Django 3.0 on 2022-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EllisTest',
            fields=[
                ('username', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ellistest',
            },
        ),
    ]
